### ISSUE TITLE
你好，CtClass有些类取的有问题

### ISSUE THREAD

**Issue by hetianlong0** [ltshddx/jaop#5]
你好：
       我运行了代码，发现开始的时候报null：ctClass.getPackageName().startsWith("jaop.domain") 这行。我修改plugin，进行了判空的处理；但是代码再进入 在 （TransformFileUtils.groovy）if (ctClass.getAnnotation(Jaop) != null) 这行上一直无法判断为真，查找了原因是因为一些类的解析出错。ctClass.getName() 如下：

get class's name is: android.support.v4.app.NotificationCompatBase$UnreadConversation
get class's name is: android.support.v4.view.KeyEventCompat$KeyEventVersionImpl
get class's name is: demo\jaop\sample\MainActivity

MainActivity类解析错误报：Method threw 'java.lang.RuntimeException' exception. Cannot evaluate javassist.JaopCtClass.toString()；类似的JaopDemo类也报这样的错误，导致无法植入代码；

  目前的 情况是app的类基本上都无法解析，都报错，导致也无法取得注解等信息，我想请问，这样的错误的原因是什么，可能是哪里出错了？   我将@Jaop,  @Replace("demo.jaop.sample.MainActivity.onCreate")等注解都注释了也还是报上面那个错误。
   非常感谢！

**Comment by ltshddx** [comment]
能否提供下最小可运行的demo，你的运行环境、gradle版本

**Comment by hetianlong0** [comment]
[AopDemo-master2.zip](https://github.com/ltshddx/jaop/files/1709544/AopDemo-master2.zip)

android studio 2.3.1  classpath 'com.android.tools.build:gradle:2.3.1'

**Comment by hetianlong0** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

**Comment by ltshddx** [comment]
您好，请提供一个有问题的jaop的sample，不是你自己的插件工程
你的zip在TransformFileUtils里面少了2个import
import jaop.domain.annotation.Before
import jaop.domain.annotation.After

**Comment by hetianlong0** [comment]
你好：
       AopDemo-master2.zip 这个zip下有app工程，这个app工程使用的就是你的仓库的工程。只是将@Jaop, @Replace, @After等注解去掉了。之所以有buildSrc 编译插件，是因为，使用仓库的原始例子的时候报了if (ctClass.getAnnotation(Jaop) != null) 这一行代码有null。我为了查找ctClass.getAnnotation(Jaop)的原因改写了下结构。发现有些类获取的有问题，报Method threw 'java.lang.RuntimeException' exception. Cannot evaluate javassist.JaopCtClass.toString()。
     在ASMHelper 中，在310行（ for (MethodNode methodNode : classNode.methods) {），348行（for (MethodNode methodNode : classNode.methods) {）， android studio 倒是有提示 ： 需要一个object,但是却是一个MethodNode; 另外我使用的jdk是 1.8 。
     有问题的jaop的sample，就是仓库的原始工程。
      谢谢！

**Comment by ltshddx** [comment]
我这边跑sample和你的demo都没有你说的问题，请检查是不是你的环境有问题，你是windows用户么

**Comment by hetianlong0** [comment]
对，win10。我其它的工程编译没有问题。可能环境配置不一样吧。在我的机器上编译：获取的类名有些是：get class's name is: demo\jaop\sample\MainActivity  这样的格式。出现这样格式的类名就解析不了。
       非常感谢你的耐心帮助！

**Comment by ltshddx** [comment]
试试 classpath 'jaop.gradle.plugin:gradle-plugin:1.0.4'

**Comment by hetianlong0** [comment]
你好：
      我使用了新的版本，发现前二个bug已经被修复了。但是碰到了另外的问题，代码中我添加了一些打印日志。在JaopDemo中，我注释掉了@Replace("**")，因为编译它的话报很多错误。但是仍然碰到了null的问题。以下是我添加的一些打印。

      :app:transformClassesWithJaopForDebug
================jaop start================
read all class file cost 0.133 second
enter ctClass.getAnnotation class's name is: demo.jaop.sample.JaopDemo
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="demo.jaop.sample.MainActivity.onCreate")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="android.widget.Toast.makeText")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="android.support.v7.app.AppCompatActivity.onCreate")

enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="android.app.Activity+.getActionBar")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="demo.jaop.sample.Foo.say")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="demo.jaop.sample.Zoo.new")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="demo.jaop.sample.Zoo.say")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="demo.jaop.sample.MainActivity.Main.onClick")
enter ctClass.declaredMethods.each
enter object 1 is: @jaop.domain.annotation.Replace(value="**.new")
has regex demo.jaop.sample.JaopDemo replaceAll
check all class cost 3.65 second, class count: 1461
[ERROR] null, at demo.jaop.sample.MainActivity.onCreate(android.os.Bundle)
[ERROR] null, at demo.jaop.sample.MainActivity.getActionBar()
jaop cost 21.321 second
================jaop   end================
   

报错
 [ERROR] null, at demo.jaop.sample.MainActivity.onCreate(android.os.Bundle)
[ERROR] null, at demo.jaop.sample.MainActivity.getActionBar() 
jaop cost 21.321 second

**Comment by hetianlong0** [comment]
我的工程在附件中。
[AopDemo-master2.zip](https://github.com/ltshddx/jaop/files/1713556/AopDemo-master2.zip)
    我发现仓库的工程 应该是studio 和 gradle 版本较低，我的android studio 是2.3.1； 要是在你的机器上没有问题的话，应该就是我们的android studio 版本不一致造成的。

    另外还有一个问题，aspectJ对方法的hook有 call, execution, around等方式，一般是或者wrap,或者replace;目前我对仓库的工程不熟悉，看例子都是replace的方式，仓库中代码已经实现了wrap的方式了吗？假如没有实现的话，未来会进行添加wrap方式的功能吗？

**Comment by ltshddx** [comment]
你的demo用的asm版本低了，请使用原版的sample，在此基础上改
//    compile files('libs/asm-debug-all-5.0.2.jar')
    compile 'org.ow2.asm:asm-debug-all:5.2'
用5.2
wrap和replace 对于jaop来说没有区别，所以只会有3种，before、 after、 replace。满足了所有情况

**Comment by hetianlong0** [comment]
你好：
        现在例子程序已经没有问题了，非常感谢！
        对于wrap和replace来说，replace是完全替换函数体，但是有些程序的写法替换函数体后会有负作用，比如有些类库可能使用了一些技巧，使用了原来函数的地址，这样replace方法就会导致程序不能正常工作了。这时候，使用wrap方法就不会有问题，aspectJ在使用wrap后，也还有 @AfterReturning，这样调用原来的函数后，它通过该方法可以获取原来函数的返回值。
       我的一个疑问是，假如一个函数替换后有负作用的话（使用wrap)

**Comment by hetianlong0** [comment]
你好：
       现在的仓库工程在我这里已经没有问题了。非常感谢！
       我还有几个疑问，想请教一下。  
       1） getActionBar() 返回 ActionBar，为何在@replace 函数中是  void replace4(MethodBodyHook hook) ，该替换函数好像并没有将返回值传递回去。@replace的函数体的替换原理是什么样子的，为何替换函数可以不传递返回值？
       2）仓库例子中的replace函数的参数有2种，一种是MethodCallHook，一种是MethodBodyHook，这2个参数的函数是如何区分的，什么情况使用MethodCallHook, 什么情况使用MethodBodyHook?
       3)   还是关于@replace的问题。aspectJ有 wrap和replace2种方式，有些工程的代码，直接替换掉函数有负作用，比如它在代码中记录了原来函数的地址，实现一些编程的技巧。假如直接使用replace的时候可能会导致问题，但是这时候使用wrap的方式，然后在通过AfterReturning获得返回值就不会有问题。那jop直接使用@replace一种方式会不会在某些情况下不能覆盖说有情况呢?

**Comment by ltshddx** [comment]
1、为了aop规则的适用性，返回值被封装在MethodBodyHook的getResult()里面，字节码会在hook处自动处理，具体原理看代码
2、MethodCallHook，指的是方法被调用处的aop；MethodBodyHook指的是方法体内部的aop。
3、这种方式不予支持
望知晓。
